---
title: "Assignment 1: Introduction"
author: "Joy Wu"
output: pdf_document
---

## OVERVIEW

This exercise accompanies the introductory material in Environmental Data Analytics. 

## Directions
1.  Rename this file `<FirstLast>_A01_Introduction.Rmd` (replacing `<FirstLast>` with your first and last name).
2.  Change "Student Name" on line 3 (above) with your name.
3.  Work through the steps, **creating code and output** that fulfill each instruction.
4.  Be sure to **answer the questions** in this assignment document.
5.  When you have completed the assignment, **Knit** the text and code into a single PDF file.
6.  After Knitting, submit the completed exercise (PDF file) to the appropriate assignment section on Canvas.


## 1) Discussion Questions
Enter answers to the questions just below the >Answer: prompt.

1. What are your previous experiences with data analytics, R, and Git? Include both formal and informal training.

> Answer: My previous data analytics experiences include using Python and Excel to build models, specifically for energy topics. I have taken both ENV 716 and ENV 717 where I used both tools extensively to build predictive energy models through running simulations. This summer, I also used Excel to build figures, using data I extrated from Bloomberg Terminal, to support my analyses at work. I have not used R and Git previously. 

2. Are there any components of the course about which you feel confident?

> Answer: I am more confident about the actual data analysis part where we focus more on the data.

3. Are there any components of the course about which you feel apprehensive?

> Answer: The process of using RStudio and Github and linking them with each other seems a little bit complicated for me, and I am worried that I would mess up one of the steps along the way to not sync my data across platforms properly. 


## 2) GitHub

Provide a link below to your forked course repository in GitHub. Make sure you have pulled all recent changes from the course repository and that you have updated your course README file, committed those changes, and pushed them to your GitHub account. 

> Answer: https://github.com/jzwu01/EDE_Fall2025.git

## 3) Knitting
When you have completed this document, click the `knit` button.This should produce a PDF copy of your markdown document. Submit this PDF to Canvas 
